os:       linux
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

matrix:
    include:
        - name: "OSX"
          os: osx
          language: python

install:
    - echo "Env var TRAVIS_OS_NAME ${TRAVIS_OS_NAME}"
    - echo "Env var WANTED_PYTHON_VERSION ${WANTED_PYTHON_VERSION}"
    - echo "Current directory ${CWD}"
    - python --version
    - pip --version
    - pip install setuptools
    - python setup.py install

script:
    - cr download program:object-detection-tf-py --version=1.0.0 --all
