os:       linux
language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

matrix:
    include:
        - name: "OSX with Python 3.6"
          os: osx
          language: generic
          python:   3.6

install:
    - echo "Env var TRAVIS_OS_NAME ${TRAVIS_OS_NAME}"
    - echo "Env var WANTED_PYTHON_VERSION ${WANTED_PYTHON_VERSION}"
    - echo "Current directory ${CWD}"
    - python --version
    - pip --version
    - pip install setuptools
    - python setup.py install

script:
    - cr download program:mlperf-inference-v0.5.open.object-detection --version=1.0.0 --all
