os:       linux
dist:     xenial
sudo:     false

language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"

matrix:
    include:
        - name: "Python 3.6.7 on Bionic/amd64"
          os: linux
          arch: amd64
          dist: bionic
          python: 3.6.7
        - name: "Python 3.6.8 on OSX"
          os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.6
          env:      WANTED_PYTHON_VERSION=3.6

addons:
    apt:
        packages:
            - python-pip

before_install:
    - | 
        if [ "$WANTED_PYTHON_VERSION" == "2.7" ]; then
            export PYTHON_EXE=python
        else
            export PYTHON_EXE=python3
        fi

install:
    - echo "Env var TRAVIS_OS_NAME ${TRAVIS_OS_NAME}"
    - echo "Env var WANTED_PYTHON_VERSION ${WANTED_PYTHON_VERSION}"
    - echo "Current directory ${CWD}"
    - ${PYTHON_EXE} -m pip install setuptools
    - ${PYTHON_EXE} setup.py install

script:
    - cr download program:mlperf-inference-v0.5.open.object-detection --version=1.0.0 --all
