os:       linux
language: python

python:
    - "2.7"

matrix:
    include:
        - os: osx
          osx_image: xcode9.2
          language: python
          python:   3.6

install:
    - echo "Env var TRAVIS_OS_NAME ${TRAVIS_OS_NAME}"
    - echo "Env var WANTED_PYTHON_VERSION ${WANTED_PYTHON_VERSION}"
    - echo "Current directory ${CWD}"
    - python --version
    - pip --version
    - pip install setuptools
    - python setup.py install

script:
    - cr download package:lib-tensorflow-pip --all
